### ISSUE TITLE
Can't install brunch on Windows 10 - Error: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by bxqgit** [brunch/brunch#1740] opened 2017-08-28 22:56 UTC
### Description

Can't install brunch on Windows 10

### Expected behavior

I expect `npm install -g brunch` to install `brunch` without errors.

### Actual behavior

1. No antivirus installed. Windows protection is turned off.
2. All commands are run in as Administrator.

```
npm install -g brunch

C:\Users\foo\AppData\Roaming\npm\brunch -> C:\Users\foo\AppData\Roaming\npm\node_modules\brunch\bin\brunch
npm ERR! path C:\Users\foo\AppData\Roaming\npm\node_modules\brunch\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\foo\AppData\Roaming\npm\node_modules\brunch\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\foo\AppData\Roaming\npm\node_modules\brunch\node_modules\fsevents\node_modules\abbrev\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\brunch\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\brunch\\node_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\foo\AppData\Roaming\npm-cache\_logs\2017-08-28T22_49_59_863Z-debug.log
```
### Environment

Brunch:
```
Can't install it. That's the problem.
```
Node.js:
```
v8.4.0
```
NPM:
```
5.4.0
```
Operating system:
```
Microsoft Windows [Version 10.0.15063]
```

**Comment by shvaikalesh** [comment] 2017-09-05 20:14
Hello there, @bxqgit.

Please try

```
npm install -g brunch --no-optional
```

**Comment by rendall** [comment] 2017-09-07 10:41
I, for one, came here to report the same problem, tried @shvaikalesh 's solution and was able to install.

**Comment by rendall** [comment] 2017-09-07 17:37
@bxqgit Try rolling back to 5.3.0.  `npm i -g npm@5.3.0` There is likely an issue with 5.4.0

**Comment by SirDev** [comment] 2017-09-07 21:59
@rendall Thanks for this tip, I've had all kinds of permission issues (on windows) unrelated to this project and this fixed me.

**Comment by shvaikalesh** [comment] 2017-09-07 22:42
I will go ahead and close this issue. Please reopen if the the problem is in Brunch core.

**Closed by shvaikalesh** 2017-09-07 22:42 UTC
