### ISSUE TITLE
Generate standalone UMD bundle (?)

### ISSUE THREAD

**Issue by pjanik** [brunch/brunch#908] opened 2015-01-12 08:51 UTC
I'm using Brunch to build my library. Default CommonJS wrappers work fine unless someone is using RequireJS too. Then `require.register` fails, because it's simply undefined in RequireJS implementation of `require`.

On the other hand, if I switch to `amd` module wrapping, then no wrappers are provided at all. I assume that I should do it manually, as well as I should include RequireJS or RequireJS shim (e.g. almond). But that's overkill in my case.

What about something similar to `browserify --standalone` option? It worked great for me in other projects. It generates UMD bundle which works fine in every case:
 - Export to global namespace (window)
 - CommonJS
 - AMD / RequireJS

Info can be found in readme:
https://github.com/substack/node-browserify

And here is a real life example of generated package:
https://github.com/concord-consortium/lab-grapher/blob/master/dist/lab-grapher.js#L1

That would also solve another, smaller issue - to export my library API to global namespace (well, window object), I have to provide a tiny module:
`window.MyLib = require('scripts/my-lib');`
and make sure that it's not wrapped in CommonJS definitions. I'm doing that so users can just include JS file and they can use `MyLib` instead of manually calling `require(...)`.

**Comment by es128** [comment] 2015-01-12 11:27
Dupe of #713. PR welcome.

**Closed by es128** 2015-01-12 11:27 UTC
