### ISSUE TITLE
`brunch watch` crashes if watched file is removed and re-added

### ISSUE THREAD

**Issue by dalexj** [brunch/brunch#1332] opened 2016-05-02 17:52 UTC
### Description

running `brunch watch`, if a file gets cached, removed, and then re-added - brunch crashes

### Expected behavior

brunch reads the new file and recompiles

### Actual behavior

brunch watch crashes with this error:

```
/path/to/my/project/node_modules/brunch/lib/fs_utils/file_list.js:138
    file.removed = false;
                 ^

TypeError: Cannot assign to read only property 'removed' of #<SourceFile>
  at FileList.compile (/path/to/my/project/node_modules/brunch/lib/fs_utils/file_list.js:138:18)
  at /path/to/my/project/node_modules/brunch/lib/fs_utils/file_list.js:201:16
  at /path/to/my/project/node_modules/fcache/index.js:21:5
  at tryToString (fs.js:414:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

### Environment

1. Brunch: 2.7.4
2. Node: 5.4.1
3. NPM: 3.3.12
4. Operating system: OSX

**Comment by r-zzi** [comment] 2016-05-03 00:57
It seemed to me that it could be related to https://github.com/brunch/brunch/issues/1320 and I reproduced this problem in the last production version and checked it after my changes (https://github.com/brunch/brunch/pull/1333). As I see this problem is fixed too. 
I guess it is related to the fact that removed files are still present is the list, but have "freezed" state since they were disposed earlier.

**Comment by goshakkk** [comment] 2016-05-10 15:05
@dalexj can you see if the latest brunch fixes this one for you? The PR @r-zzi mentions has been already merged

**Closed** 2016-05-10 17:21 UTC
