### ISSUE TITLE
Adding react through config.npm throws:  Cannot find module 'c:\code\brunchtest\node_modules\react\lib\React.js\package.json'

### ISSUE THREAD

**Issue by mordra** [brunch/brunch#1094] opened 2016-01-06 01:20 UTC
On windows 8, simple test app with react throws a compile error:
```
$ brunch watch --server                                                                      
06 Jan 12:15:30 - info: application started on http://localhost:3333/                        
module.js:340                                                                                
    throw err;                                                                               
    ^                                                                                        
                                                                                             
Error: Cannot find module 'c:\code\brunchtest\node_modules\react\lib\React.js\package.json'  
  at Function.Module._resolveFilename (module.js:338:15)                                     
  at Function.Module._load (module.js:289:25)                                                
  at Module.require (module.js:366:17)                                                       
  at require (module.js:385:17)                                                              
  at filePath (c:\code\brunchtest\node_modules\brunch\lib\deppack.js:55:33)                  
  at filePath (c:\code\brunchtest\node_modules\brunch\lib\deppack.js:58:37)                  
  at Object.keys.filter.forEach (c:\code\brunchtest\node_modules\brunch\lib\deppack.js:73:17)
  at generateModule (c:\code\brunchtest\node_modules\brunch\lib\deppack.js:101:14)           
  at c:\code\brunchtest\node_modules\brunch\lib\deppack.js:157:13                            
  at tryToString (fs.js:414:3)                                                               
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)                             
```

brunch-config
```
'use strict';  
    exports.config = {
      files: {
        javascripts: {
          joinTo: 'app.js'
        }
      },
      plugins: {
        browserSync: {
          port: 3336
          //,logLevel: "debug"
        },
        babel: {
          presets: ['es2015'],
          pattern: /\.(es6|jsx|js)$/
        }
      },
      npm:{
        enabled: true
      }
    };
```
package.json
```
{
      "name": "your-app",
      "description": "Description",
      "author": "Your Name",
      "version": "0.0.1",
      "repository": {
        "type": "git",
        "url": ""
      },
      "scripts": {
        "start": "brunch watch --server"
      },
      "dependencies": {
        "babel-brunch": "^6.0.0",
        "browser-sync-brunch": "0.0.9",
        "brunch": "^2.1.1",
        "clean-css-brunch": ">= 1.0 < 1.9",
        "css-brunch": ">= 1.0 < 1.9",
        "javascript-brunch": ">= 1.0 < 1.9",
        "react": "^0.14.5",
        "react-dom": "^0.14.5",
        "uglify-js-brunch": ">= 1.0 < 1.9"
      }
    }
```

**Comment by jondlm** [comment] 2016-01-07 05:40
I think you have to add `config.npm.whitelist`, in addtion to your `config.npm.enabled`, which is an array of whitelisted packages. See if that helps.

**Comment by mordra** [comment] 2016-01-07 05:56
I did add that without success, then I read a bit more and it says that any packages without brunch will be added to the front end.

Also, all the whitelist does is actually makes it available to package for the front end, the fact that the error is **looking** in the react module should mean that it is being whitelisted shouldn't it?

**Comment by jondlm** [comment] 2016-01-07 06:02
Yeah, I'm not sure beyond that :confused:

**Comment by mordra** [comment] 2016-01-07 09:42
I think he's sorting it out in the other issue as part of a whole NPM rewrite. Looks like there are still alot of existing issues. I've gone back to webpack for the time being but not happy about how complex it is to do anything. Thanks for trying to help.

**Comment by paulmillr** [comment] 2016-01-07 12:02
@mordra Brunch 2.1 requires `whitelist` to be specified; Brunch 2.2 would not require that. We're in the process of making Brunch figure out the package list based on app's code.

**Comment by goshakkk** [comment] 2016-01-19 16:28
@mordra the master version of brunch both got rid of `whitelist` in favor of automatically figuring out what should be added to the bundle, as well as should support fs separators other than `/` (aka `\`) on windows. Can you try it with `npm install -g brunch/brunch` and report how it goes?

**Comment by mordra** [comment] 2016-01-22 01:06
I've got the master branch of brunch but what's really annoying right now is that something is causing my package not to work and there are no console errors.

```
<script>console.log('test javascript is enabled!');</script>
<script type="text/javascript" src="delivered.js"/>
<script>
    console.log('hi');
    require('jsfile').init();
</script>
```
This logs 'javascript is enabled' and then goes silent. Nothing...
If I remove the delivered.js reference, then it logs 'hi' and require is undefined (expected). No network issues, no errors.

I've even gone back the most basic app.js/html/css example and I'm not able to get brunch working at all... very frustrating.

Chucked a debugger statement in the `delivered.js` and no errors there either. But it just wouldn't run the next script tag.

**Comment by goshakkk** [comment] 2016-01-22 09:35
@mordra could it be the case that you forgot to run `npm install` after adding `react` to `package.json`? I just copied your snippets locally and it works like a charm:

```
br-react-test$ brunch b
22 Jan 12:25:47 - info: compiled 158 files into delivered.js, copied index.html in 4 sec
```

**Comment by mordra** [comment] 2016-01-22 11:49
O_O... it could be. Local version at work, I'll try it first thing monday and update this comment. Thanks for your help!

**Comment by mordra** [comment] 2016-01-24 22:34
@goshakkk Unfortunately no luck, i did `npm i` but react was already installed.

I also started a new project just with my snippets and did a `npm i` followed by `brunch b`, same error.

**Comment by paulmillr** [comment] 2016-01-25 01:37
@mordra try brunch 2.2 which just hit npm

**Comment by mordra** [comment] 2016-01-25 01:41
@paulmillr  I did this but it looks like it's still failing...
The code I'm using is an exact copy of my snippet in a new folder.

```
$ npm update brunch

$ npm list brunch                                                                                  
your-app@0.0.1 c:\code\brunchtemp                                                                  
└── brunch@2.2.0                                                                                   

$ brunch b                                                                                         
25 Jan 12:38:44 - error: undefined of app\jsfile.js failed. Cannot find module 'react' from 'app'  
```

**Comment by paulmillr** [comment] 2016-01-25 02:06
could you try this? `npm install brunch/brunch`

**Comment by mordra** [comment] 2016-01-25 02:30
It gave me a different error which means I'm probably picking up the 2.2.0 version now but still same issue:
I'm on windows 8.1 if it makes any difference, I can try this on a ubuntu 14.04 machine later too.

```
$ npm i brunch/brunch
npm WARN install Couldn't install optional dependency: Unsupported
your-app@0.0.1 c:\code\brunchtemp
└── brunch@2.2.0  (git://github.com/brunch/brunch.git#e5afcde4c8b1719d9e71434edfa27e1866a67252)

npm WARN EPACKAGEJSON your-app@0.0.1 No license field.

$ brunch b
25 Jan 13:26:43 - error: Resolving deps of app\jsfile.js failed. Could not load module 'react' from 'app'. Possible solution: run `npm install`.

$ npm i
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPACKAGEJSON your-app@0.0.1 No license field.

$ brunch b
25 Jan 13:26:55 - error: Resolving deps of app\jsfile.js failed. Could not load module 'react' from 'app'. Possible solution: run `npm install`.
```

**Comment by goshakkk** [comment] 2016-01-25 09:29
@mordra windows dep resolution issues were caused by https://github.com/substack/node-resolve which didn't properly supply lookup paths. My pull-request to address that was already merged; brunch/brunch#1125 should bump this dep in brunch

**Comment by paulmillr** [comment] 2016-01-25 15:35
@mordra I have merged the pull request; please uninstall brunch and execute `npm install brunch/brunch` again.

**Closed** 2016-01-26 19:06 UTC

**Comment by mordra** [comment] 2016-01-26 22:46
I can confirm my snippets works on v2.2.1 on win8.1 and ubuntu 14.04
Thanks for the speedy fixes :) (sorry I didn't respond yesterday, Australia day national holiday over here)

**Comment by jouana** [comment] 2016-02-05 23:55
hi,

I try react with brunch and i have one problem since i use babel-brunch with preset react.
Brunch read my dependencies but they aren't injected in my bundle.

You can find my code here -> here https://github.com/jouana/test_react

I do not see my mistake :s

**Comment by jouana** [comment] 2016-02-06 12:33
Hi all,

Ok my bad I used pattern: /\.jsx$/ for plugin babel and must use that   pattern: /\.(js|jsx)$/
It's ok all work well.
Thanks and have a good day
