### ISSUE TITLE
NPM Show stopper with Cheesy work-around

### ISSUE THREAD

**Issue by jahbini** [brunch/brunch#1309] opened 2016-04-22 21:03 UTC
I am using Brunch with some coffeeScript inside a node module.  Brunch recognizes it as coffeescript, and tags the correct compiler, but the routine 'isNPM' is called just before the proper compiler should be called.  The assumption is that NPM modules are all cooked, and no compilation step is necessary.  The routine returns true, and the compilation is skipped.

However, `isNPM` also checks to see if this might be in a Brunch plugin, by checking if the path contains `-brunch` or `brunch-`.

So all I needed to do to get my coffescript compiled is to name the subdirectory it is in to `brunch-payload`.  this way `isNPM` returns false, and my coffescript gets compiled and finds it's proper home in app.js.

However, this "feature" is not documented, and possibly unintended.  I'd vote to include the capability to get my coffescript compiled -- no matter what way that might happen.

Just sayin'

**Comment by goshakkk** [comment] 2016-04-23 07:33
> The assumption is that NPM modules are all cooked

And it's a correct assumption. Module's consumers should not care to know how it was authored; it is up to the module to provide proper javascript output.

Now, there are some genuine edge cases to this, like modules authored in ES6 and browser not supporting it, in which case the compilation step probably should happen (not implemented yet, https://github.com/brunch/brunch/issues/1300)

The mechanism implemented to resolve that issue might allow to compile module's coffeescript, but I wouldn't rely on it. Just make your module produce javascript, as that would both remove the wait on that issue and ultimately be more in line from the conceptual overlook.

**Comment by goshakkk** [comment] 2016-04-23 07:38
> So all I needed to do to get my coffescript compiled is to name the subdirectory it is in to brunch-payload. this way isNPM returns false, and my coffescript gets compiled and finds it's proper home in app.js.

Yup, that seems like unintended behavior. `isNpm` was originally intended to exclude plugins' vendor files from going through dependency resolution, etc... This will be fixed.

**Comment by jahbini** [comment] 2016-04-23 07:47
The fact that the coffescript must be cooked is a show stopper -- Mostly it means that the source stories must be re-engineered into non-NPM modules, and put somewhere else.

But frankly, isn't the whole idea of Brunch is to offload this kind of computation?

**Comment by goshakkk** [comment] 2016-04-23 07:52
Well, the idea of NPM modules is to provide ready-to-use, no-additional-steps-necessary code, isn't it?

Either way, it could get possible when I work to address #1300, but I personally wouldn't do something like that. YMMV. (Subscribe to that issue if you feel like it)

**Comment by jahbini** [comment] 2016-04-24 00:30
I looked some info over on the NPM documentation site.  (https://docs.npmjs.com/getting-started/creating-node-modules) The first sentence said "Node.js modules are one kind of package which can be published to npm. When you create a new module, you want to start with the package.json file."

So modules may be Another Kind -- that has other content (coffescript source, markdown source, prayers to the Flying Spaghetti Monster, etc) that might well be entrusted to Brunch.

I'm happy to supply any kind of hint to Brunch that you may come up with.

**Comment by goshakkk** [comment] 2016-04-25 07:55
At least for the time being, it looks like we'll be implementing a simpler and implicit way to only compile ES6 npm modules — see https://github.com/brunch/brunch/issues/1300#issuecomment-213689404

**Comment by goshakkk** [comment] 2016-06-17 08:41
@paulmillr can be closed I guess.

**Closed** 2016-06-18 10:42 UTC
Labels: bug
