### ISSUE TITLE
Files appears to be copied twice in debug

### ISSUE THREAD

**Issue by nervo** [brunch/brunch#1008] opened 2015-08-12 18:50 UTC
Maybe it's just an artefact, but all copied files appeared twice in debug log

    brunch:file-list Copied asset 'app/Resources/assets/fonts/toto/black.eot' +4ms
    brunch:file-list Copied asset 'app/Resources/assets/fonts/toto/black.eot' +1ms
    brunch:file-list Copied asset 'app/Resources/assets/fonts/toto/black.svg' +1ms
    brunch:file-list Copied asset 'app/Resources/assets/fonts/toto/black.svg' +1ms

Any clue ?

**Comment by GesJeremie** [comment] 2015-09-21 01:02
@nervo Can you give us more details ?

**Comment by nervo** [comment] 2015-09-21 18:35
Of course :)

    $ brunch -V                
    1.8.5

Given a simple structure

    ├── app
    │   └── Resources
    │       └── assets
    │           └── fonts
    │               └── black.eot
    ├── brunch-config.coffee
    ├── node_modules
    │   ...
    ├── package.json
    └── web
        ...

a *brunch-config.coffee* like this:

    exports.config =
      paths:
        public:  'web/assets'
        watched: [
          'app/Resources/assets'
        ]
      conventions:
        assets: /assets[\\/](?!sass|js)/
      files:
        stylesheets:
          joinTo: 
            'css/main.css': /sass\/main/
            'css/login.css': /sass\/login/

Give us a brunch debug log:

    $ brunch build -d          
      brunch:watch Loaded plugins: javascript-brunch, css-brunch, sass-brunch, auto-reload-brunch, imageoptmizer-brunch +0ms
      brunch:watch File 'app/Resources/assets' received event 'addDir' +9ms
      brunch:watch File 'package.json' received event 'add' +16ms
      brunch:watch File 'brunch-config.coffee' received event 'add' +1ms
      brunch:watch File 'app/Resources/assets/fonts' received event 'addDir' +4ms
      brunch:asset Initializing fs_utils.Asset {"path":"app/Resources/assets/fonts/black.eot","directory":"app/Resources/assets/","relativePath":"fonts/black.eot","destinationPath":"web/assets/fonts/black.eot"} +4ms
      brunch:watch File 'app/Resources/assets/fonts/black.eot' received event 'add' +1ms
      brunch:file-list Copied asset 'app/Resources/assets/fonts/black.eot' +4ms
      brunch:file-list Copied asset 'app/Resources/assets/fonts/black.eot' +0ms
      brunch:write Writing 0/0 files +67ms
    21 Sep 20:29:52 - info: copied black.eot in 300ms

See ? *black.eot* is referenced twice in the debug log. Not a big deal, but a little strange...

**Comment by ghostd** [comment] 2015-12-04 22:01
I can't reproduce this with the master branch.
@paulmillr @es128 ?

**Comment by es128** [comment] 2015-12-04 22:18
@nervo have you been able to reproduce this with brunch v2?

One other idea is that perhaps a symlink is involved.

**Comment by paulmillr** [comment] 2015-12-05 17:45
Closing until someone reproduces this with 2.0.

**Closed by paulmillr** 2015-12-05 17:45 UTC

**Comment by nervo** [comment] 2015-12-06 12:40
Yep, good solution.
I no longer use brocoli, but i guess that if this issue remains, someone will notify :)
