### ISSUE TITLE
Modules off option does not working

### ISSUE THREAD

**Issue by happyCoda** [brunch/brunch#1712] opened 2017-05-21 13:50 UTC
### Description

It seems that modules.off option does not work.

### Expected behavior

According to brunch docs modules.off option should prevent plugin from using.

### Actual behavior

However, when I am using:

```javascript
plugins: {
    off: ['eslint-brunch']
}
```
eslint plugin still lints my js files.

### Environment

1. Brunch: 2.10.9
1. Node.js: 7.10.0
1. NPM: 4.2.0
1. Operating system: macOS Sierra
1. Code editor: Atom

### `package.json` contents

```json
{
  "name": "test-app",
  "version": "0.1.0",
  "main": "index.js",
  "devDependencies": {
    "auto-reload-brunch": "^2.7.1",
    "babel-brunch": "^6.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint-brunch": "^3.12.0",
    "jasmine-core": "^2.6.1",
    "karma-brunch": "^1.0.6",
    "karma-spec-reporter": "0.0.31",
    "less-brunch": "^2.10.0",
    "vue-brunch": "^2.0.1"
  },
  "dependencies": {
    "vue": "^2.3.3"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "happyCoda",
  "license": "MIT"
}
```

### brunch config contents

```javascript
module.exports = {
  paths: {
    watched: ['app', 'specs']
  },
  files: {
    javascripts: {
      joinTo: {
        'js/bundle.js': /^app\/js|(.|\/)*node_modules/,
        'specs/bundle.spec.js': /^specs/
      }
    },
    stylesheets: {
      joinTo: 'css/bundle.css'
    }
  },
  modules: {
    autoRequire: {
      'js/bundle.js': ['js/main'],
      'specs/bundle.spec.js': ['specs/app.spec']
    }
  },
  sourceMaps: false,
  plugins: {
    off: ['eslint-brunch'],
    eslint: {
      pattern: /^app\/js\/.*.js$/
    },
    karma: {
      singleRun: true,
      basePath: 'public',
      browsers: ['PhantomJS'],
      frameworks: ['jasmine'],
      reporters: ['spec'],
      specReporter: {
        maxLogLines: 5,         // limit number of lines logged per test
        suppressErrorSummary: true,  // do not print error summary
        suppressFailed: false,  // do not print information about failed tests
        suppressPassed: false,  // do not print information about passed tests
        suppressSkipped: true,  // do not print information about skipped tests
        showSpecTiming: false // print the time elapsed for each spec
      },
      files: [
        'js/bundle.js',
        'js/bundle.spec.js'
      ]
    }
  }
};
```

I've tried to log config contents from brunch/lib/utils/plugins.js and discover that config.plugins.off is an empty array. After that I've added overrides option in my config:

```javascript
overrides: {
    development: {
      plugins: {
        off: ['eslint-brunch']
      }
    }
  }
```

And after that elsint-brunch has been disabled. But I think this is not expected behaviour.

**Comment by denysdovhan** [comment] 2017-05-22 05:59
Hi @happyCoda! Thanks for reaching out!

I'm gonna take a look at this problem. Can you create a repo for easier reproducing of your problem?

**Comment by shvaikalesh** [comment] 2017-05-22 06:31
Looks like `skemata`'s fault. Fixed in #1664 (and covered by real tests).

**Comment by denysdovhan** [comment] 2017-05-22 10:19
@shvaikalesh You're welcome. I don't touch this problem then.

**Comment by wiltzius** [comment] 2017-06-17 21:12
Does anyone know what Brunch version introduced this bug?

**Closed** 2021-08-07 20:41 UTC
