### ISSUE TITLE
Debugging projects using the builtin WebStorm interface

### ISSUE THREAD

**Issue by mcfarljw** [brunch/brunch#1386] opened 2016-06-02 23:17 UTC
I'm wondering if anyone has been using the builtin WebStorm debugger with their Brunch projects? I stumbled across a tutorial on their blog describing how to configure it for webpack bundles:

https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/

I haven't had any luck following it and getting it to work with Brunch though. It'd be fairly snazzy if it was possible though, because setting breakpoints and such directly from the editor would be a debugging timesaver. Any thoughts? How do you go about debugging your Brunch projects?

**Comment by paulmillr** [comment] 2016-08-10 16:23
I usually add `debugger;` statements in code; that helps a lot.

**Comment by mvanstelle** [comment] 2017-05-11 19:26
You can vote for native support for Brunch in WebStorm here! https://youtrack.jetbrains.com/issue/WEB-17962

**Comment by shvaikalesh** [comment] 2017-05-11 22:46
Duplicate of #1668.

**Closed by shvaikalesh** 2017-05-11 22:46 UTC
Labels: feature
