### ISSUE TITLE
Sourcemaps for Typescript files not displaying correctly in Chrome using Brunch 2.10.9

### ISSUE THREAD

**Issue by Ennas** [brunch/brunch#1689] opened 2017-03-24 18:17 UTC
### Description

Building my Typescript project using brunch does not include correct sourcemapping in the browser anymore. I noticed this starts breaking in 2.10.0 (so I'm using 2.9.1 for now).

### Expected behavior

I expect to see Typescript code when I open the mapped files in the browser for debugging.

### Actual behavior

Chrome still shows .ts source files, but when I open them the content appears to be the transpiled .js files.

### Environment

1. Brunch: 2.10.9
1. Node.js: 6.9.1
1. NPM: 3.10.9
1. Operating system: Windows 7
1. Code editor: VSCode

### `package.json` contents

```
{
  "name": "myapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "my-other-app": "1.0.0-alpha005"
  },
  "devDependencies": {
    "brunch": "^2.10.8",
    "jasmine-core": "^2.5.2",
    "javascript-brunch": "^2.10.0",
    "less-brunch": "^2.10.0",
    "tslint": "^4.5.1",
    "typescript": "^2.2.1",
    "typescript-brunch": "^2.3.0",
    "uglify-js": "^2.8.12"
  }
}
```

### brunch config contents

```
module.exports = {
    files: {
        javascripts: {
            joinTo: {
                'js/vendor.js': /^Website.UI\/libs\/vendor\//,
                'js/app.js': /^Website.UI\/app\//
            },
            order: {
                before: ['Website.UI/libs/vendor/angular.min.js']
            }
        },
        stylesheets: {
            joinTo: 'css/main.css'
        },
    },
    plugins: {
        brunchTypescript: {
          ignoreErrors: true
        }
    },
    paths: {
        watched: ['Website.UI\/app\/', 'Website.UI\/libs\/vendor\/', 'Website.UI\/less\/'],
        public: 'Website.UI\/public'
    },
    modules: {
        nameCleaner: (path) => path.replace(/^Website\.UI\/app\//, ''),
        autoRequire: {
            'js/app.js': ['app']
        }
    }
}
```

**Comment by denysdovhan** [comment] 2017-03-24 22:13
Not sure, but seems like I had the same problem last few days. Thanks for reaching us out! Gonna take a look at this and try to solve.

**Comment by shvaikalesh** [comment] 2017-03-24 22:37
It is a well-known source maps issue caused by compiler chaining. Progress in #1664.

**Comment by phillipp** [comment] 2017-06-13 16:34
@shvaikalesh The issue you references is just a long list of more references. Which one is the one I need to look into to get this fixed on my app?

**Comment by shvaikalesh** [comment] 2017-06-13 17:40
@phillipp #1664 will certainly fix many issues, including this one. for now, you can downgrade to `~2.9`.

**Comment by phillipp** [comment] 2017-06-13 18:18
@shvaikalesh Thanks, but the problem persists in 2.9.1.

I still have no idea what the specific list item in #1664 is, that will fix this. Or are you talking about an unspecified "there will be a fix in 3.0 that I will reference in issue 1664 but it isn't there yet"

**Comment by shreeve** [comment] 2017-10-10 01:38
I submitted pull request #1756 as a possible fix for broken sourcemaps on Brunch 2.10

I really am not sure what this would potentially break, but in my case it seemed to fix sourcemaps which have not been working for a while. In fact, I was able to see the original source for both coffeescript and vue single file components (*.vue files).

Let me know if this is correct or way outta line...

**Comment by jkruse** [comment] 2017-10-10 07:04
Also see #1635

**Comment by friday** [comment] 2017-10-17 19:21
Perhaps #1757 solves this?

**Closed** 2021-08-07 21:11 UTC
Labels: chaining
