### ISSUE TITLE
Docs on npm integration

### ISSUE THREAD

**Issue by fny** [brunch/brunch#991] opened 2015-06-26 12:18 UTC
Reading around the issues pages, it looks like some level of npm integration has been added via deppack, but I'm not sure what I need to do to get it working. This is the closest tidbit I've managed find:

> At the time of this writing, the Brunch team is hard at work to provide first-class integration with npm, which will greatly ease isomorphic JS and will let us use our node_modules-installed code transparently inside our front-end application code, as modules still. Until then, we’ll need to hack around with the Browserify plugin for Brunch plugin.

What are the steps to get this working? I'm running the Brunch v1.8.3.

**Comment by es128** [comment] 2015-06-26 14:56
In the simplest form, you simply `npm install` your dependencies and then `require` what you need in your application code. You also need `npm: enabled: true For many dependencies this should work fine, but there are many cases not yet addressed in an elegant way.

You can see some more discussion on it at

https://github.com/brunch/brunch/pull/987
https://github.com/brunch/brunch/issues/986
https://github.com/brunch/brunch/issues/984

**Comment by es128** [comment] 2015-07-10 16:23
Reopening - even though the OP's question was answered, we need more info in the actual docs

**Comment by ondreian** [comment] 2015-07-14 18:08
So, I thought it'd be nice to swap from bower to npm in a few of my skeletons this morning, and am having no success getting it to concat the npm modules into the compiled application.

I have: 
  `npm: enabled: true` in my brunch config 
  the latest version of brunch downloaded from npm

The goal being just to be able to run a `require 'jquery'` and `require 'mithril'` from my node_modules directory in the app.

[here is a repo with the skeleton in question.](https://github.com/ondreian/brunch-mithril-surge)

I'm on windows 7, using the latest version of Node.js (though i've tested it with a few versions).

**Comment by es128** [comment] 2015-07-14 18:36
Probably a bug. Try seeing if switching to vanilla js works any better.

**Comment by ondreian** [comment] 2015-07-14 19:32
Thanks, I see what the problem is, it doesn't parse those .js extension files in the node_modules directory without having `javascript-brunch` installed as a plugin.

One more bug is that it is trying to define them as:
```javascript
require.register('C:\dev\brunch-skeleton\mithril-surge\node_modules\jquery\dist\jquery.js', //the rest
```
Instead of just the npm module name

**Comment by lpil** [comment] 2015-08-30 09:31
Hello! using npm modules is still rather confusing with brunch. Could we get this documentation update please?

**Comment by paulmillr** [comment] 2015-09-28 15:59
Let's move to gh-1023.

**Closed by paulmillr** 2015-09-28 15:59 UTC
