### ISSUE TITLE
the watcher compiles a changed file as an empty file

### ISSUE THREAD

**Issue by maxlath** [brunch/brunch#971] opened 2015-05-12 12:56 UTC
I'm having this weird, exhausting issue since a few weeks.
The pattern seems to be this one: when I edit a file, around 1/10 of the times the file updated just before is compiled as empty.

Brunch shows no error, I got to detect the error from `ReferenceErrors` and alikes (when it's an empty js module) or missing DOM elements (when it's an empty handlebars template) that show up as the module is empty, getting me paranoid on every error: "is that coming from my code or from this random f*** bug?". I generally solve it by re-editing the empty file to force it to be recompiled.

The logs don't seem to show anyting (debug mode):
```
12 May 14:40:27 - info: compiled initialize.coffee and 328 cached files into app.js in 1271ms
  brunch:file-list Reading 'app/modules/comments/comments.coffee' +28s
  brunch:watch File 'app/modules/comments/comments.coffee' received event 'change' +0ms
  brunch:pipeline Compiling 'app/modules/comments/comments.coffee' with 'CoffeeScriptCompiler' +1ms
  brunch:helpers Wrapping '"modules/comments/comments"' with commonjs +20ms
  brunch:source-file Generated source map for 'app/modules/comments/comments.coffee'  +0ms
  brunch:file-list Compiled file 'app/modules/comments/comments.coffee'... +6ms
  brunch:write Writing 1/4 files +72ms
  brunch:generate Concatenating [some files], app/initialize.coffee, [LOTS of files] to public/javascripts/app.js +375ms
  brunch:common Writing file 'public/javascripts/app.js' +363ms
  brunch:common Writing file 'public/javascripts/app.js.map' +290ms
12 May 14:40:56 - info: compiled comments.coffee and 328 cached files into app.js in 1134ms
```
and as a result I get
```
;require.register("initialize", function(exports, require, module) {

});
```
instead of 
```
;require.register("initialize", function(exports, require, module) {
   [my module code here]
});
```

Here is my config file:
```
exports.config =
  notifications: yes
  sourceMaps: true
  files:
    javascripts:
      defaultExtension: "coffee"
      joinTo:
        'javascripts/vendor.js': /^(vendor\/scripts|bower_components)/
        'javascripts/app.js': /^app/
      order:
        before: [
          "bower_components/jquery/dist/jquery.js"
          "bower_components/underscore/underscore.js"
          "bower_components/backbone/backbone.js"
        ],
        after: [
          "vendor/*"
        ]

    stylesheets:
      defaultExtension: "scss"
      joinTo:
        'stylesheets/vendor.css': /^(vendor\/stylesheets|bower_components\/(?!foundation))/
        'stylesheets/app.css': /^app/

    templates:
      joinTo: 'javascripts/app.js'
  overrides:
    production:
      sourceMaps: true
      optimize: true
```
and the whole project actually: [inventaire-client](https://github.com/maxlath/inventaire-client/)

From what I can remember, when the bug started I was using brunch 1.8 and auto-reload-brunch 1.7.8, I tried to revert to older versions (brunch 1.7.20 and auto-reload-brunch 1.7.4) without success

my devDependencies
```
 "devDependencies": {
    "auto-reload-brunch": "^1.7.4",
    "brunch": "^1.7.20",
    "bower": "^1.4.1",
    "browserify": "^9.0.8",
    "chai": "^2.2.0",
    "clean-css-brunch": "^1.7.2",
    "coffee-script-brunch": "^1.8.1",
    "css-brunch": "^1.7.0",
    "git-digest-brunch": "^1.0.3",
    "graceful-fs": "^3.0.6",
    "handlebars": "^3.0.1",
    "handlebars-brunch": "^1.9.1",
    "html-minifier": "^0.7.2",
    "javascript-brunch": "^1.7.1",
    "ls": "^0.1.0",
    "mkdirp": "^0.5.0",
    "mocha": "^2.2.4",
    "sass-brunch": "^1.8.10",
    "sinon": "^1.14.1",
    "uglify-js-brunch": "^1.7.8"
  }
```

any idea of what could be happening? thanks in advance! :sos:

**Comment by es128** [comment] 2015-05-12 13:44
Most likely a race condition between your text editor and Brunch. What OS and editor are you using? 

The way the editor is saving files is probably to wipe out the file first, then write it with the new contents. But the change event would have already been triggered, and Brunch may have already read the file before the new contents were written. See if you can turn off a setting in your editor for "atomic" writes, or try a different one.

Is it more likely to happen with larger files? If so, another strategy (which would likely be helpful for other reasons as well) would be to refactor your code into smaller chunks.

**Comment by es128** [comment] 2015-05-12 13:45
And on the Brunch side, a potential solution to make this more seamless to users would be to always retry reading a file after a delay if it goes from having contents to empty after a change event.

**Comment by maxlath** [comment] 2015-05-12 16:49
I'm on a Ubuntu 12.04 with Sublime Text (Build 3083). It might very well be due to the last version of Sublime, I will have a look at that, thanks for the lead!
I don't think it's an issue with the file size as the [initialize file](https://github.com/maxlath/inventaire-client/blob/master/app/initialize.coffee) makes less than 20 lines.

**Comment by maxlath** [comment] 2015-05-12 17:57
wow, there was a [change in the Sublime Text default `atomic_save` setting](http://stackoverflow.com/a/20639093/3324977), so it might very much be that!! It seems that I can't reproduce the bug since I reverted the change to `atomic_save=true`, but you can't reproduce a random when you want to, can you? I will wait a bit before opening the champagne and closing the issue. Thank you @es128 !!

**Comment by es128** [comment] 2015-05-12 18:24
The issue probably shouldn't be closed as long as the possibility of Brunch detecting a newly emptied file and retrying remains open

**Comment by kursion** [comment] 2015-08-03 14:49
I have the same problem since few days. Using latests vim version.

**Comment by kursion** [comment] 2015-08-03 15:40
I wouldn't expect that but, setting `backupcopy` to `"auto"` fixed the issue.

**Comment by maxlath** [comment] 2015-08-04 16:27
I went into this same empty file bug when using `git stash` :/

**Comment by matthopson** [comment] 2015-08-06 22:21
I can reproduce this pretty consistently with SB2 - I've always worked around it, telling myself I would eventually look into why it happens - but have yet to do so.

If I go into a file and select a block of code and comment it out with ` cmd ` + ` / ` - it will compile an empty file every single time. A co-worker is also plagued consistently by this issue in vim. I'll be digging into it a bit deeper.

**Comment by maxlath** [comment] 2015-08-06 22:38
@matthopson have you tried to set `atomic_save=true` in Sublime? It seem to have solve my problem with SublimeText3

**Comment by matthopson** [comment] 2015-08-06 23:36
Yeah, tried that, with no difference.

**Comment by jarkonik** [comment] 2015-09-15 21:18
Already references here: https://github.com/brunch/brunch/issues/354 with possible workaround.

**Comment by hughes** [comment] 2015-12-20 21:51
Can also confirm that setting `atomic_save=true` in Sublime Text 3 solved this.

**Comment by tprk77** [comment] 2016-01-02 01:21
This is affecting me as well. I'm on Xubuntu 14.04, Node 4.2.4, Brunch 2.0.4.

I'm using Emacs 24.5.1. I also saw the issue using Mousepad 0.4.0 (the Xubuntu default editor). I could not reproduce the issue using Nano 2.4.2. (Weirdly enough, using Emacs it works for the first save after starting `brunch w`, but not for any following save.)

I don't think Emacs has an "atomic save" option...

**Comment by tprk77** [comment] 2016-01-02 01:40
Tested again with Brunch 2.1.0 and I'm still running into this problem.

I did notice something about the Emacs save though:

> C-x C-s runs the command save-buffer, which is an interactive compiled Lisp function.
>
> It is bound to C-x C-s, <menu-bar> <file> <save-buffer>.
>
> (save-buffer &optional ARG)
>
> Save current buffer in visited file if modified.
> Variations are described below.
>
> By default, makes the previous version into a backup file
> if previously requested or if this is the first save.

So it looks like it's moving the file and then writing a new one. I think that makes sense, seems to explain the issue. (I guess Mousepad is doing something similar, too.)

**Comment by tprk77** [comment] 2016-01-07 15:08
Pull request #1093 added a new flag to the watcher config called `awaitWriteFinish`. If you set it, the compile should work despite whatever your editor is doing. @maxlath do you think we can close this issue?

**Comment by maxlath** [comment] 2016-01-07 17:48
@tprk77 the Sublime parameter was the fix for me, so I didn't test your solution, but from what I can see, it seems to address the right problem. So if the project maintainers agree, I guess that can be closed indeed

**Closed** 2016-01-07 17:59 UTC

**Comment by LeG3nDz** [comment] 2016-03-31 14:03
Hi,

I've same problem, but i use brackets editor.
