### ISSUE TITLE
"Cannot read property 'split' of undefined" when renaming file

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1614] opened 2016-12-31 12:17 UTC
### Description

When renaming a file while `brunch watch`ing, brunch shows a confusing "Cannot read property 'split' of undefined" error.

This issue is split out from #1604.

### Expected behavior

Here's what happens if you rename a file _before_ starting the watcher. I guess that's what should show up when renaming _after_ starting the watcher as well.

```
$ mv app/utils.js app/helpers.js
$ brunch w
31 Dec 13:13:01 - error: Processing of app/one.js failed.

   Could not load module 'utils' from '/home/lydell/src/brunch-notification-overflow/app'. Possible solution: add 'utils' to package.json and `npm install`.
 
31 Dec 13:13:01 - error: Processing of app/three.js failed.

   Could not load module 'utils' from '/home/lydell/src/brunch-notification-overflow/app'. Possible solution: add 'utils' to package.json and `npm install`.
 
31 Dec 13:13:01 - error: Processing of app/two.js failed.

   Could not load module 'utils' from '/home/lydell/src/brunch-notification-overflow/app'. Possible solution: add 'utils' to package.json and `npm install`.
 
31 Dec 13:13:01 - info: compiled helpers.js into app.js in 347 ms
```

### Actual behavior

Here's the test repo: https://github.com/lydell/brunch-notification-overflow

```
$ brunch w &
31 Dec 13:09:47 - info: compiled 4 files into app.js in 416 ms
$ mv app/utils.js app/helpers.js
31 Dec 13:09:51 - info: compiled helpers.js and 4 cached files into app.js in 72 ms
31 Dec 13:09:52 - error: Processing of app/one.js failed.

   Cannot read property 'split' of undefined
 
31 Dec 13:09:52 - error: Processing of app/three.js failed.

   Cannot read property 'split' of undefined
 
31 Dec 13:09:52 - error: Processing of app/two.js failed.

   Cannot read property 'split' of undefined
 
```

### Environment

1. Brunch: commit afefc5e7643f37918ed037e3862461624e483425
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu Gnome 16.04

### `package.json` contents

```json
{
  "private": true,
  "devDependencies": {
    "brunch": "github:brunch/brunch#afefc5e7643f37918ed037e3862461624e483425",
    "javascript-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  }
}
```

**Comment by shvaikalesh** [comment] 2016-12-31 19:40
Hello there, @lydell.

Thanks for your dedication in helping Brunch project. We appreciate that much.
Indeed, that is a bug in resolving/packing Node's modules.
I have improved a bit error message with https://github.com/brunch/deppack/commit/80c3d8a2fc8d36856513bfb1f03c9ffab2508c6a.

I will create a meta issue of issues are caused by `deppack`. I estimate resolving all them vs replacing `deppack` with *better solution* close in terms of time, but latter will result in (by far) healthier code base, first-class ES6 modules support etc.

**Comment by lydell** [comment] 2017-01-01 12:14
Thank you all who work on the brunch team! Your level of support and maintenance has been very high last year, and that is very much appreciated.

I trust you to make the best decision on how to fix issues like these. Take the time needed! This is a non-critical bug, after all.

**Closed** 2021-08-07 20:34 UTC
Labels: deppack
